export const TOGGLE_FAVOURITE_CITY = "TOGGLE_FAVOURITE_CITY"
export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER"
export const SET_5DAY_FORECAST_WEATHER = "SET_5DAY_FORECAST_WEATHER"
export const TOGGLE_CANVAS = "TOGGLE_CANVAS"
